### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by MyYuan** [xiaoping6688/vue-spa-project#2]
![image](https://user-images.githubusercontent.com/13746191/31476363-9573a300-af38-11e7-85d2-d5e141607a32.png)
and when i execute npm run build error

**Comment by xiaoping6688** [comment]
fixed

**Comment by MyYuan** [comment]
？

**Comment by MyYuan** [comment]
I installed eslint alone, and still reported it wrong，Can you explain in more detail how to solve it?
